#!/bin/bash

# Installs all JAR from lib to a local maven repository

MAVEN_REPO=maven-repo

[[ -d $MAVEN_REPO ]] || mkdir $MAVEN_REPO

for j in $(ls lib/*.jar); do
  JBASE=$(basename $j)
  JNAME=${JBASE%%.jar}

  #TODO -versioning if the JAR has it
  mvn -q install:install-file -Dfile=$j -DartifactId=$JBASE -Dversion=1.0.0 -DgroupId=local -Dpackaging=jar -DlocalRepositoryPath=maven_repo -DcreateChecksum=true
done

