#!/bin/bash

# Installs all JAR from lib to a local maven repository

REPO=maven-repo

[[ -d $REPO ]] || mkdir $REPO

for j in $(ls lib/*.jar); do
  JBASE=$(basename $j)
  JNAME=${JBASE%%.jar}

  #TODO -versioning if the JAR has it
  mvn -q install:install-file -Dfile=$j -DartifactId=$JBASE -Dversion=1.0.0 -DgroupId=local -Dpackaging=jar -DlocalRepositoryPath=$REPO -DcreateChecksum=true
done

